name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - pip:
      - numpy==1.24.1
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/LMHan122/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
      - databricks_cli==0.8.7
